"""empty message

Revision ID: 053c3b99ca54
Revises: 974035c1c095
Create Date: 2025-02-11 15:34:44.666671

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "053c3b99ca54"
down_revision: Union[str, None] = "974035c1c095"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
