"""empty message

Revision ID: 198322360a6f
Revises: 015f14e040b4
Create Date: 2025-02-11 15:28:29.671562

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "198322360a6f"
down_revision: Union[str, None] = "015f14e040b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
