"""empty message

Revision ID: 6998a3d80791
Revises: 053c3b99ca54
Create Date: 2025-02-11 15:36:36.919643

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6998a3d80791"
down_revision: Union[str, None] = "053c3b99ca54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
