"""empty message

Revision ID: 6a31e02750e2
Revises: f702a6ae79a0
Create Date: 2025-02-11 15:17:53.669859

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6a31e02750e2"
down_revision: Union[str, None] = "f702a6ae79a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
