"""empty message

Revision ID: 974035c1c095
Revises: 99dd41418ac1
Create Date: 2025-02-11 15:33:52.676957

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "974035c1c095"
down_revision: Union[str, None] = "99dd41418ac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
