"""empty message

Revision ID: 99dd41418ac1
Revises: 198322360a6f
Create Date: 2025-02-11 15:32:01.290184

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "99dd41418ac1"
down_revision: Union[str, None] = "198322360a6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
