"""empty message

Revision ID: a18173c28366
Revises: 6a31e02750e2
Create Date: 2025-02-11 15:20:55.993612

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a18173c28366"
down_revision: Union[str, None] = "6a31e02750e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
