"""empty message

Revision ID: bf7a12d253b4
Revises: e9844712ef6d
Create Date: 2025-02-12 20:50:45.620419

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bf7a12d253b4"
down_revision: Union[str, None] = "e9844712ef6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
