"""empty message

Revision ID: c89a2a10da26
Revises: 4b76cd404231
Create Date: 2025-02-11 15:14:13.216134

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c89a2a10da26"
down_revision: Union[str, None] = "4b76cd404231"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
