"""empty message

Revision ID: f702a6ae79a0
Revises: c89a2a10da26
Create Date: 2025-02-11 15:15:34.415023

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f702a6ae79a0"
down_revision: Union[str, None] = "c89a2a10da26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
